//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/ScriptableObjects/Input/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""CanCrasher"",
            ""id"": ""705c1fcb-80e9-4983-9d13-f6740016c781"",
            ""actions"": [
                {
                    ""name"": ""Tap"",
                    ""type"": ""Button"",
                    ""id"": ""25c0b6d4-61b8-448f-88d9-bffd00736067"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4384059f-8fb7-4b50-b885-1c6267c24767"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f670a03f-d33f-4d3b-aca0-c1ef63c611e1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CanCrasher
        m_CanCrasher = asset.FindActionMap("CanCrasher", throwIfNotFound: true);
        m_CanCrasher_Tap = m_CanCrasher.FindAction("Tap", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CanCrasher
    private readonly InputActionMap m_CanCrasher;
    private List<ICanCrasherActions> m_CanCrasherActionsCallbackInterfaces = new List<ICanCrasherActions>();
    private readonly InputAction m_CanCrasher_Tap;
    public struct CanCrasherActions
    {
        private @GameInput m_Wrapper;
        public CanCrasherActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Tap => m_Wrapper.m_CanCrasher_Tap;
        public InputActionMap Get() { return m_Wrapper.m_CanCrasher; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CanCrasherActions set) { return set.Get(); }
        public void AddCallbacks(ICanCrasherActions instance)
        {
            if (instance == null || m_Wrapper.m_CanCrasherActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CanCrasherActionsCallbackInterfaces.Add(instance);
            @Tap.started += instance.OnTap;
            @Tap.performed += instance.OnTap;
            @Tap.canceled += instance.OnTap;
        }

        private void UnregisterCallbacks(ICanCrasherActions instance)
        {
            @Tap.started -= instance.OnTap;
            @Tap.performed -= instance.OnTap;
            @Tap.canceled -= instance.OnTap;
        }

        public void RemoveCallbacks(ICanCrasherActions instance)
        {
            if (m_Wrapper.m_CanCrasherActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICanCrasherActions instance)
        {
            foreach (var item in m_Wrapper.m_CanCrasherActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CanCrasherActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CanCrasherActions @CanCrasher => new CanCrasherActions(this);
    public interface ICanCrasherActions
    {
        void OnTap(InputAction.CallbackContext context);
    }
}
